// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGztsoRX1RD8flls5c2K6mXa8IoX6lZLM',
    appId: '1:733032382091:web:f65041fb1fdf44fcc75e8e',
    messagingSenderId: '733032382091',
    projectId: 'crypto-list-app-a0548',
    authDomain: 'crypto-list-app-a0548.firebaseapp.com',
    storageBucket: 'crypto-list-app-a0548.appspot.com',
    measurementId: 'G-XJNJVHWQRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2O8q50cf4_Hf0LH4dmg2RkMsZyV_Om3Y',
    appId: '1:733032382091:android:a7636a207fc5b5d9c75e8e',
    messagingSenderId: '733032382091',
    projectId: 'crypto-list-app-a0548',
    storageBucket: 'crypto-list-app-a0548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6BStarz19DrSyBHjTwLLzoTnq-uZHjDg',
    appId: '1:733032382091:ios:b052fb23da0d2a64c75e8e',
    messagingSenderId: '733032382091',
    projectId: 'crypto-list-app-a0548',
    storageBucket: 'crypto-list-app-a0548.appspot.com',
    iosClientId: '733032382091-qm5c715no2sgl1f1eeeopo5tplt2g052.apps.googleusercontent.com',
    iosBundleId: 'com.example.superCryptocurrencies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6BStarz19DrSyBHjTwLLzoTnq-uZHjDg',
    appId: '1:733032382091:ios:b052fb23da0d2a64c75e8e',
    messagingSenderId: '733032382091',
    projectId: 'crypto-list-app-a0548',
    storageBucket: 'crypto-list-app-a0548.appspot.com',
    iosClientId: '733032382091-qm5c715no2sgl1f1eeeopo5tplt2g052.apps.googleusercontent.com',
    iosBundleId: 'com.example.superCryptocurrencies',
  );
}
